name: CI/CD MkDocs

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Récupération du dépôt
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Installation de Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.9"

      # 3) Installation de MkDocs et des plugins
      - name: Install MkDocs and plugins
        run: |
          pip install --upgrade pip
          pip install mkdocs mkdocs-material mkdocs-drawio

      # 4) Génération de la documentation
      - name: Build MkDocs documentation
        run: mkdocs build --clean

      # 5) Déploiement vers GitHub Pages
      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
